name: Update Feed
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: osmoscraft/osmosfeed@v2
        with:
          config-file: osmosfeed.yaml
